name: Validate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{github.token}}
        
      - name: Setup Java JRE
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.x
          java-package: jre
          architecture: x64
     
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          check-latest: true

      - name: Install ajv JSON schema validator
        run: sudo npm i -g ajv-cli@latest
      
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@2.1.1

      - name: Validate FHIR resources
        run: chmod +x ./validate.sh && ./validate.sh
