name: Validate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JRE
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.x
          java-package: jre
          architecture: x64
     
      - name: Setup Node.js environment and install ajv-cli
        run: apt-get update && apt-get install node-ajv
      
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@2.1.1

      - name: Validate FHIR resources
        run: chmod +x ./validate.sh && ./validate.sh
